name: Run Bull & Bear Bot Daily

on:
  schedule:
    - cron: '10 12 * * *'  # 🕒 Runs every day at 5:40 PM IST
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Bull & Bear Bot
        run: node buy-both.js